/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.41).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Song;
import io.swagger.model.Songs;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-03-04T01:37:48.013595613Z[GMT]")
@Validated
public interface SongsApi {

    @Operation(summary = "Delete Song", description = "Delete song by songName, can only be done by a logged in user", security = {
        @SecurityRequirement(name = "basicAuth")    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Ok", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Songs.class))) })
    @RequestMapping(value = "/songs/{songName}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Songs> deleteSong(@Parameter(in = ParameterIn.PATH, description = "Song name of song that needs to be deleted", required=true, schema=@Schema()) @PathVariable("songName") String songName);


    @Operation(summary = "Get specific song", description = "Retrieves a specific song based on the artist", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Ok", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Song.class))),
        
        @ApiResponse(responseCode = "404", description = "Song not found") })
    @RequestMapping(value = "/songs/{artist}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Song> getSongByArtist(@Parameter(in = ParameterIn.PATH, description = "Song artist", required=true, schema=@Schema()) @PathVariable("artist") String artist);


    @Operation(summary = "Get specific song", description = "Retrieves a specific song based on the songName", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Ok", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Song.class))),
        
        @ApiResponse(responseCode = "404", description = "Song not found") })
    @RequestMapping(value = "/songs/{songName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Song> getSongByName(@Parameter(in = ParameterIn.PATH, description = "Song Name", required=true, schema=@Schema()) @PathVariable("songName") String songName);


    @Operation(summary = "Get all songs", description = "Retrieves all songs", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Songs.class))) })
    @RequestMapping(value = "/songs",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Songs> getSongs();


    @Operation(summary = "Add a song", description = "Post allowing song to be added to the database", security = {
        @SecurityRequirement(name = "basicAuth")    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Created", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Songs.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid song supplied"),
        
        @ApiResponse(responseCode = "401", description = "Unautharized"),
        
        @ApiResponse(responseCode = "403", description = "Forbidden") })
    @RequestMapping(value = "/songs",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Songs> postSong(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Song body);


    @Operation(summary = "Update song", description = "Update a song by songName, can only be done by a logged in user", security = {
        @SecurityRequirement(name = "basicAuth")    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "No Content", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Song.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid song supplied"),
        
        @ApiResponse(responseCode = "401", description = "Unautharized"),
        
        @ApiResponse(responseCode = "404", description = "Song not found") })
    @RequestMapping(value = "/songs/{songName}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Song> updateSongByName(@Parameter(in = ParameterIn.PATH, description = "Song name of song that needs to be updated", required=true, schema=@Schema()) @PathVariable("songName") String songName, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Song body);

}

